# Generated by Django 5.0.6 on 2024-06-29 10:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shortner", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="urls",
            new_name="URL",
        ),
    ]
